### PR TITLE
Test feature

### PR DESCRIPTION
**Pull request by xls**
check this bad code out!

### CODE REVIEW

**Review by jimhelm — APPROVED** [review]
This is indeed some bad code.  Since I'm assuming that's the point, I approve.  Many of the warnings given are really nice.

**Comment by xls** [comment]
I'm not going to check this in until you change comment!

- [ ] fix the comment

**Comment by jimhelm** [comment]
What do you want me to change it to?

**Comment by xls** [comment]
- [ ] fix this
- [ ] fix this too

**Comment by jimhelm** [comment]
> * [x]  fix this
> * [x]  fix this too

What am I fixing?

**Pull request merged**
